[thresholds]
low = 35
high = 65
persistence = 2

[bbands]
optInTimePeriod = 20
optInNbDevUp = 2
optInNbDevDn = 2
optInMAType = 2

[macd]
optInFastPeriod = 10
optInSlowPeriod = 21
optInSignalPeriod = 9

[ultosc]
optInTimePeriod1 = 7
optInTimePeriod2 = 14
optInTimePeriod3 = 28

[custom]
keepCurrency = 0.90
