[thresholdsHigh]
low = 45
high = 55
persistence = 2

[thresholdsLow]
low = 35
high = 45
persistence = 2

[thresholdsSecondary]
low = 50

[bbands]
optInTimePeriod = 20
optInNbDevUp = 2
optInNbDevDn = 2
optInMAType = 2

[macd]
optInFastPeriod = 10
optInSlowPeriod = 21
optInSignalPeriod = 9

[ultosc]
optInTimePeriod1 = 7
optInTimePeriod2 = 14
optInTimePeriod3 = 28

[ultosc2]
optInTimePeriod1 = 28
optInTimePeriod2 = 56
optInTimePeriod3 = 112

[custom]
priceMod = 0
uoMod = 0
maxLongs = 3
maxLongsMod = 3
persistenceMod = 3
