[thresholdsHigh]
low = 45
high = 55
persistence = 2

[thresholdsLow]
low = 30
high = 40
persistence = 3.5

[thresholdsSecondary]
low = 33
absoluteLow = 28

[bbands]
optInTimePeriod = 20
optInNbDevUp = 2
optInNbDevDn = 2
optInMAType = 2

[macd]
optInFastPeriod = 10
optInSlowPeriod = 21
optInSignalPeriod = 9

[ultosc]
optInTimePeriod1 = 7
optInTimePeriod2 = 14
optInTimePeriod3 = 28

[ultosc2]
optInTimePeriod1 = 28
optInTimePeriod2 = 56
optInTimePeriod3 = 112

[custom]
priceMod = 0
uoMod = 0
maxLongs = 5
maxLongsMod = 3
persistenceMod = 1.5